// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521074017_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.ApprovalRoleMap", b =>
                {
                    b.Property<Guid>("approval_role_map_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("legacy_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("approval_role_map_id");

                    b.ToTable("approval_role_map", (string)null);
                });

            modelBuilder.Entity("api.Models.ApprovalStatus", b =>
                {
                    b.Property<Guid>("approval_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("approval_role_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("is_approved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("approval_id");

                    b.HasIndex("user_id");

                    b.ToTable("approval_status", (string)null);
                });

            modelBuilder.Entity("api.Models.BagianUser", b =>
                {
                    b.Property<int>("bagian_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bagian_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("fungsi_id")
                        .HasColumnType("int");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("bagian_id");

                    b.ToTable("BagianUser", (string)null);
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Property<Guid>("kategoribar_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("namakategoribar")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("kategoribar_id");

                    b.ToTable("kategori_barang", (string)null);
                });

            modelBuilder.Entity("api.Models.CategoryEmployee", b =>
                {
                    b.Property<string>("kategori_pekerja_id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("nama_kategori")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("kategori_pekerja_id");

                    b.ToTable("kategori_pekerja", (string)null);
                });

            modelBuilder.Entity("api.Models.CategoryTransaction", b =>
                {
                    b.Property<string>("kategori_transact_id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("nama_kategori_transact")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("kategori_transact_id");

                    b.ToTable("kategori_transaksi", (string)null);
                });

            modelBuilder.Entity("api.Models.Employee", b =>
                {
                    b.Property<Guid>("pekerja_temp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("bagian_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("fungsi_pekerja")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("id_finger")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("link_file_pendukung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("nama_pekerja")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("perusahaan_pekerja")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("synced_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("pekerja_temp_id");

                    b.HasIndex("bagian_id");

                    b.ToTable("pekerjaTemp", (string)null);
                });

            modelBuilder.Entity("api.Models.FungsiUser", b =>
                {
                    b.Property<int>("fungsi_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fungsi_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("fungsi_id");

                    b.ToTable("FungsiUser", (string)null);
                });

            modelBuilder.Entity("api.Models.Item", b =>
                {
                    b.Property<Guid>("barang_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("jumlah_barang")
                        .HasColumnType("int");

                    b.Property<Guid>("kategoribar_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("link_gambar_bar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("msl_barang")
                        .HasColumnType("int");

                    b.Property<string>("nama_barang")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("satuanbar_id")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("status_bar")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("barang_id");

                    b.HasIndex("kategoribar_id");

                    b.HasIndex("satuanbar_id");

                    b.ToTable("barang", (string)null);
                });

            modelBuilder.Entity("api.Models.Permission", b =>
                {
                    b.Property<Guid>("permission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("permission_id");

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("api.Models.Role", b =>
                {
                    b.Property<Guid>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("role_id");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("api.Models.RolePermission", b =>
                {
                    b.Property<Guid>("role_permission_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("permission_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("role_permission_id");

                    b.HasIndex("permission_id");

                    b.HasIndex("role_id");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("api.Models.SigapUser", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("bagian_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("nama")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("refresh_token")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("username")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("user_id");

                    b.HasIndex("bagian_id");

                    b.ToTable("SIGAPUser", (string)null);
                });

            modelBuilder.Entity("api.Models.TransactionDetail", b =>
                {
                    b.Property<Guid>("transact_detail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("barang_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("jumlah_bar")
                        .HasColumnType("int");

                    b.Property<Guid>("transact_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("transact_detail_id");

                    b.HasIndex("barang_id");

                    b.HasIndex("transact_id");

                    b.ToTable("transaksi_detail", (string)null);
                });

            modelBuilder.Entity("api.Models.TransactionHistory", b =>
                {
                    b.Property<Guid>("transact_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("approval_gudang_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("approval_manajemen_pekerja_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("approval_sectionhead_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("kategori_pekerja")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("kategori_transact_id")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("no_miv_custom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("no_miv_safety")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("pekerja_temp_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("users_cache_id")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("transact_id");

                    b.HasIndex("approval_gudang_id");

                    b.HasIndex("approval_manajemen_pekerja_id");

                    b.HasIndex("approval_sectionhead_id");

                    b.HasIndex("kategori_pekerja");

                    b.HasIndex("kategori_transact_id");

                    b.HasIndex("pekerja_temp_id");

                    b.HasIndex("users_cache_id");

                    b.ToTable("transaksi_history", (string)null);
                });

            modelBuilder.Entity("api.Models.Uom", b =>
                {
                    b.Property<string>("satuanbar_id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("nama_satuanbar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("satuanbar_id");

                    b.ToTable("satuanBarang", (string)null);
                });

            modelBuilder.Entity("api.Models.UserRole", b =>
                {
                    b.Property<Guid>("user_role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("effective_from")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("effective_to")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_primary")
                        .HasColumnType("bit");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("user_role_id");

                    b.HasIndex("role_id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("api.Models.UsersCache", b =>
                {
                    b.Property<string>("user_id")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("bagian_pekerja")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("fungsi_pekerja")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("nama_pekerja")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("user_id");

                    b.ToTable("usersCache", (string)null);
                });

            modelBuilder.Entity("api.Models.ApprovalStatus", b =>
                {
                    b.HasOne("api.Models.UsersCache", "usersCacheDto")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usersCacheDto");
                });

            modelBuilder.Entity("api.Models.Employee", b =>
                {
                    b.HasOne("api.Models.BagianUser", "BagianUserDto")
                        .WithMany("Employees")
                        .HasForeignKey("bagian_id");

                    b.Navigation("BagianUserDto");
                });

            modelBuilder.Entity("api.Models.Item", b =>
                {
                    b.HasOne("api.Models.Category", "categoryDto")
                        .WithMany("ItemDto")
                        .HasForeignKey("kategoribar_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Uom", "uomDto")
                        .WithMany("Item")
                        .HasForeignKey("satuanbar_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoryDto");

                    b.Navigation("uomDto");
                });

            modelBuilder.Entity("api.Models.RolePermission", b =>
                {
                    b.HasOne("api.Models.Permission", "PermissionDto")
                        .WithMany("RolePermissions")
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Role", "RoleDto")
                        .WithMany("RolePermissions")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionDto");

                    b.Navigation("RoleDto");
                });

            modelBuilder.Entity("api.Models.SigapUser", b =>
                {
                    b.HasOne("api.Models.BagianUser", "BagianUserDto")
                        .WithMany("SigapUsers")
                        .HasForeignKey("bagian_id");

                    b.Navigation("BagianUserDto");
                });

            modelBuilder.Entity("api.Models.TransactionDetail", b =>
                {
                    b.HasOne("api.Models.Item", "itemDto")
                        .WithMany()
                        .HasForeignKey("barang_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.TransactionHistory", "TransactionHistory")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("transact_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransactionHistory");

                    b.Navigation("itemDto");
                });

            modelBuilder.Entity("api.Models.TransactionHistory", b =>
                {
                    b.HasOne("api.Models.ApprovalStatus", "ApprovalGudangIdDto")
                        .WithMany()
                        .HasForeignKey("approval_gudang_id");

                    b.HasOne("api.Models.ApprovalStatus", "ApprovalManajemenPekerjaIdDto")
                        .WithMany()
                        .HasForeignKey("approval_manajemen_pekerja_id");

                    b.HasOne("api.Models.ApprovalStatus", "ApprovalSectionheadIdDto")
                        .WithMany()
                        .HasForeignKey("approval_sectionhead_id");

                    b.HasOne("api.Models.CategoryEmployee", "CategoryEmployeeDto")
                        .WithMany("TransactionHistorys")
                        .HasForeignKey("kategori_pekerja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.CategoryTransaction", "CategoryTransactionsDto")
                        .WithMany("TransactionHistorys")
                        .HasForeignKey("kategori_transact_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Employee", "EmployeeDto")
                        .WithMany("TransactionHistorys")
                        .HasForeignKey("pekerja_temp_id");

                    b.HasOne("api.Models.UsersCache", "UsersCacheDto")
                        .WithMany("TransactionHistorys")
                        .HasForeignKey("users_cache_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovalGudangIdDto");

                    b.Navigation("ApprovalManajemenPekerjaIdDto");

                    b.Navigation("ApprovalSectionheadIdDto");

                    b.Navigation("CategoryEmployeeDto");

                    b.Navigation("CategoryTransactionsDto");

                    b.Navigation("EmployeeDto");

                    b.Navigation("UsersCacheDto");
                });

            modelBuilder.Entity("api.Models.UserRole", b =>
                {
                    b.HasOne("api.Models.Role", "RoleDto")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.SigapUser", "SigapUsers")
                        .WithOne("UserRoleDto")
                        .HasForeignKey("api.Models.UserRole", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleDto");

                    b.Navigation("SigapUsers");
                });

            modelBuilder.Entity("api.Models.BagianUser", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("SigapUsers");
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Navigation("ItemDto");
                });

            modelBuilder.Entity("api.Models.CategoryEmployee", b =>
                {
                    b.Navigation("TransactionHistorys");
                });

            modelBuilder.Entity("api.Models.CategoryTransaction", b =>
                {
                    b.Navigation("TransactionHistorys");
                });

            modelBuilder.Entity("api.Models.Employee", b =>
                {
                    b.Navigation("TransactionHistorys");
                });

            modelBuilder.Entity("api.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("api.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("api.Models.SigapUser", b =>
                {
                    b.Navigation("UserRoleDto");
                });

            modelBuilder.Entity("api.Models.TransactionHistory", b =>
                {
                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("api.Models.Uom", b =>
                {
                    b.Navigation("Item");
                });

            modelBuilder.Entity("api.Models.UsersCache", b =>
                {
                    b.Navigation("TransactionHistorys");
                });
#pragma warning restore 612, 618
        }
    }
}
